#cortex_service.py
import os
import requests
import snowflake.connector


def query_cortex_analyst(prompt: str):

    conn = snowflake.connector.connect(
        user=os.getenv("SNOWFLAKE_USER"),
        password=os.getenv("SNOWFLAKE_PASSWORD"),
        account=os.getenv("SNOWFLAKE_ACCOUNT"),
        warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
        database=os.getenv("SNOWFLAKE_DATABASE"),
        schema=os.getenv("SNOWFLAKE_SCHEMA"),
        role=os.getenv("SNOWFLAKE_ROLE"),
    )

    try:

        # Get fresh token from ACTIVE session
        token = conn.rest.token
        account = os.getenv("SNOWFLAKE_ACCOUNT")

        url = f"https://{account}.snowflakecomputing.com/api/v2/cortex/analyst/message"

        payload = {
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt
                        }
                    ]
                }
            ],
            "semantic_model_file": "@DELPHI_DB.PUBLIC.DELPHI_STAGE/DELPHI_LEADS.yaml"
        }

        headers = {
            "Authorization": f'Snowflake Token="{token}"',
            "Content-Type": "application/json"
        }

        response = requests.post(
            url,
            json=payload,
            headers=headers
        )

        data = response.json()

        print("RAW CORTEX RESPONSE:", data)

        # -----------------------------------
        # HANDLE CORTEX ERRORS
        # -----------------------------------
        if "code" in data:
            print("CORTEX API ERROR:", data.get("message"))
            return []

        # -----------------------------------
        # EXTRACT GENERATED SQL
        # -----------------------------------
        sql_query = None

        for item in data["message"]["content"]:
            if item["type"] == "sql":
                sql_query = item["statement"]
                break

        if not sql_query:
            print("No SQL generated by Cortex")
            return []

        print("GENERATED SQL:")
        print(sql_query)

        # -----------------------------------
        # EXECUTE SQL IN SNOWFLAKE
        # -----------------------------------
        cursor = conn.cursor()

        try:
            cursor.execute(sql_query)

            columns = [col[0] for col in cursor.description]
            rows = cursor.fetchall()

            results = [
                dict(zip(columns, row))
                for row in rows
            ]

            print(f"[Cortex] Returned {len(results)} leads")

            return results

        finally:
            cursor.close()

    except Exception as e:
        print("CORTEX EXECUTION ERROR:", str(e))
        return []

    finally:
        conn.close()